[server]
hostname = "%{env:MAIL_HOSTNAME}%"

[server.http]
permissive-cors = true

[server.listener."smtp"]
bind = ["[::]:25"]
protocol = "smtp"

[server.listener."http"]
bind = ["[::]:8080"]
protocol = "http"

[storage]
data = "sqlite"
fts = "sqlite"
blob = "sqlite"
lookup = "sqlite"
directory = "internal"

[store."sqlite"]
type = "sqlite"
path = "%{env:STALWART_DATA_DIR}%/stalwart.sqlite3"

[directory."internal"]
type = "internal"
store = "sqlite"

[tracer."stdout"]
type = "stdout"
level = "info"
ansi = false
enable = true

[authentication.fallback-admin]
user = "admin"
secret = "%{env:ADMIN_SECRET}%"
